[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "azure-data-tables>=12.7.0",
    "azure-functions>=1.23.0"
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
